languageCode = 'en-us'
title = 'OnlyC2C'

# theme = "hugo-book"

[taxonomies]
    tag = "tags"
    category = "categories"

[markup]
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
